[tool.poetry]
name = "ankamaauth"
version = "0.1.0"
description = ""
authors = ["Valentin Alix <valentin-alix.850@outlook.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
bs4 = "^0.0.2"
requests = "^2.32.3"
thrift = "^0.20.0"
playwright = "^1.46.0"
curl-cffi = "^0.7.1"
psutil = "^6.0.0"
wmi = "^1.5.1"
pycryptodomex = "^3.21.0"
icecream = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
